### ISSUE TITLE
里面的样式为什么不写成自适应的呢？

### ISSUE THREAD

**Issue by alfie0904** [TJ666/vue-pdf-shower#1]
把#cvsWraper、.loading-pdf写死，这样别人不好用吧，我的需求刚好跟你是一样的。
顺带问一句，如何才能让他支持ssr，要改动pdf.js？

**Comment by TJ666** [comment]
下次版本更新会把样式做成可配置的，现在先暂时覆盖下吧~
ssr是用的nuxt么？文档有介绍如何引用第三方插件，配置插件只从客户端还是服务端运行。
https://zh.nuxtjs.org/guide/plugins

**Comment by alfie0904** [comment]
感谢回答，现在是按照nuxt的plugins做的，糊涂了
